### ISSUE TITLE
Order in = formulas should matter

### ISSUE THREAD

**Issue by rzach** [OpenLogicProject/fitch-checker#7]
p = q and q = p should be regarded as different formulas

![screenshot from 2018-01-12 08-55-03](https://user-images.githubusercontent.com/3122348/34883282-6bb1aefa-f776-11e7-811f-bedad4e2ac99.png)

**Comment by rzach** [comment]
Fixed in 6b21373f0d08853715b18726122b54695a0179df

**Comment by frabjous** [comment]
They definitely aren't treated as the same formula. Something different is
going on there. I'll look into it when I can.
