### ISSUE TITLE
Can one introduce an existential twice?

### ISSUE THREAD

**Issue by FrankHubeny** [OpenLogicProject/fitch-checker#9]
Looking at a post on Philosophy Stack Exchange I was able to reproduce what a user claimed a professor said was a correct derivation:  https://philosophy.stackexchange.com/q/60866/29944

![03022019-2](https://user-images.githubusercontent.com/22087147/53690819-cfcc0880-3d3f-11e9-8346-56c356e9d7d7.png)

However, I am puzzled why this is correct, but perhaps it is.

**Comment by rzach** [comment]
You may infer (∃x)A from any formula A[t/x] (the result of replacing every free occurrence of x in A by t). If A is (∃x)Fx then x has no free occurrences in it, so A[t/x] is just (∃x)Fx. Hence, you may infer (∃x)(∃x)Fx from (∃x)Fx by ∃I. (This is called vacuous quantification).
